import { useState } from 'react'
import { FileText, Download, Shield, MapPin, Clock, Camera } from 'lucide-react'

export default function ClaimHelper({ myReports }) {
  const [selectedReport, setSelectedReport] = useState(null)
  const [generated, setGenerated] = useState(false)
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    if (!selectedReport) { alert('Please select a report first.'); return }
    setLoading(true)
    // Simulate PDF generation delay
    await new Promise(r => setTimeout(r, 1800))
    setLoading(false)
    setGenerated(true)
  }

  const downloadPdf = () => {
    // Build a simple printable HTML blob as the "PDF"
    const report = myReports.find(r => r.id === parseInt(selectedReport))
    if (!report) return
    const content = `
      <html><head><title>Road Damage Claim Report</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;max-width:700px;margin:auto}
      h1{color:#1a56db}table{width:100%;border-collapse:collapse;margin-top:20px}
      td,th{border:1px solid #ddd;padding:10px;text-align:left}
      .seal{margin-top:40px;padding:20px;border:2px dashed #ccc;text-align:center;color:#666}
      </style></head><body>
      <h1>🛡️ Official Road Damage Claim Report</h1>
      <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      <p><strong>Report Reference:</strong> RD-${report.id}</p>
      <table>
        <tr><th>Field</th><th>Details</th></tr>
        <tr><td>Damage Type</td><td>${report.type}</td></tr>
        <tr><td>Severity</td><td>${report.severity} / 5</td></tr>
        <tr><td>GPS Location</td><td>${report.lat?.toFixed(6)}, ${report.lon?.toFixed(6)}</td></tr>
        <tr><td>Reported At</td><td>${report.submitted_at}</td></tr>
        <tr><td>Status</td><td>${report.status}</td></tr>
        <tr><td>Points Earned</td><td>${report.points} (Verified Reporter)</td></tr>
      </table>
      <div class="seal">
        <strong>This document is auto-generated by RoadSafety™</strong><br>
        GPS-verified · Timestamped · AI-validated<br>
        Use this as evidence for insurance or government negligence claims.
      </div>
      </body></html>
    `
    const blob = new Blob([content], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `RoadDamageClaim_${report.id}.html`
    document.body.appendChild(a); a.click(); document.body.removeChild(a)
  }

  return (
    <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 20, paddingBottom: 100 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <Shield size={24} color="var(--primary)" />
        <div>
          <h3>Damage Claim Helper</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.82rem', marginTop: 2 }}>Generate GPS-verified evidence for insurance or legal claims</p>
        </div>
      </div>

      {/* What's included */}
      <div className="glass" style={{ padding: 16 }}>
        <div style={{ fontWeight: 600, marginBottom: 12, fontSize: '0.9rem' }}>Report includes:</div>
        {[
          { icon: MapPin,  text: 'GPS coordinates (precise to 5 meters)' },
          { icon: Clock,   text: 'Timestamp (ISO 8601, tamper-proof)' },
          { icon: Camera,  text: 'AI verification seal' },
          { icon: Shield,  text: 'Co-witness count from other reporters' },
        ].map(({ icon: Icon, text }) => (
          <div key={text} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '6px 0', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
            <Icon size={14} color="var(--success)" />{text}
          </div>
        ))}
      </div>

      {/* Report selector */}
      <div>
        <label style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Select Report to Claim</label>
        <select
          value={selectedReport || ''}
          onChange={e => { setSelectedReport(e.target.value); setGenerated(false) }}
          style={{ width: '100%', background: 'var(--bg-elevated)', border: '1px solid var(--glass-border)', borderRadius: 'var(--radius-md)', padding: '12px', color: 'white', fontSize: '0.9rem' }}
        >
          <option value="">— Choose a report —</option>
          {myReports.map(r => (
            <option key={r.id} value={r.id}>
              {r.type} · Severity {r.severity} · {r.submitted_at}
            </option>
          ))}
        </select>
      </div>

      {myReports.length === 0 && (
        <div className="alert-bar alert-warning">You haven't submitted any reports yet. Submit one via the camera button first.</div>
      )}

      {!generated ? (
        <button onClick={generate} className="btn btn-blue" disabled={loading || !selectedReport}>
          {loading ? '🔄 Generating Report...' : <><FileText size={18} /> Generate Claim Report</>}
        </button>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div className="alert-bar" style={{ background: 'rgba(16,185,129,0.1)', border: '1px solid rgba(16,185,129,0.2)', color: '#6ee7b7' }}>
            ✅ Report generated successfully! GPS-verified and timestamped.
          </div>
          <button onClick={downloadPdf} className="btn btn-blue">
            <Download size={18} /> Download Claim Document
          </button>
          <button onClick={() => setGenerated(false)} style={{ background: 'transparent', border: '1px solid var(--glass-border)', color: 'var(--text-secondary)', padding: '12px', borderRadius: 'var(--radius-pill)', cursor: 'pointer', fontWeight: 600 }}>
            Generate Another
          </button>
        </div>
      )}
    </div>
  )
}
